version: '3.7'
services:
  rabbit:
    image: rabbitmq:3.6.9-management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432