fail_fast: false
repos:
-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: forbid-crlf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
