dist: xenial
language: python
services:
  - docker
python:
  - 3.6
  - 3.7
install:
  - pip install docker-compose
  - pip install -r requirements-dev.txt
script:
  - make flake
  - make tests
  - make ci