dist: xenial
language: python
services:
  - docker
python:
  - 3.6
  - 3.7
install:
  - pip install docker-compose
  - pip install -r requirements-dev.txt
script:
  - make lint  # execute flake8 and mypy
  - make tests # execute unit and integration tests
  - make ci    # publishes tests reports