[build-system]
requires = [
    "setuptools >= 46.4.0",
]
build-backend = "setuptools.build_meta"

[tool.portray]
modules = ["rabbit"]

[tool.portray.mkdocs.theme]
favicon = "docs/bunny.png"
logo = "docs/bunny.png"
name = "material"
palette = {primary = "deep-orange", accent = "gray"}

