name: 💡 Feature Request
description: Share your need or ideas about a problem to make rabbit-client better.
body:
  - type: textarea
    id: problem
    attributes:
      label: Need/Ideas Statement
      description: What your need or ideas?
      placeholder: |-
        Your description here =)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
    validations:
      required: false
