name: ci

on: [ push, pull_request ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        os: [ubuntu]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Install dependencies
      run: uv sync --dev --all-extras
    - name: Run lint & tests
      run: make ci
